### PR TITLE
added #midasIcon (= #mooseIcon) which is called somewhere ...

### PR DESCRIPTION
**Pull request by NicolasAnquetil**

### CODE REVIEW

**Comment by ClotildeToullec** [comment]
I think I just removed it while doing a pass on the inspector that was showing almost no icons.

Where is it used? Should it be? How is it different from #mooseIcon?
It just returns `self mooseIcon`, I don't get it.

**Comment by NicolasAnquetil** [comment]
As I said, it is called somewhere (inspector panel for FAST), so it needs to be defined or we need to replace its call by #mooseIcon
I would prefer the 2nd solution, but I did not have time to investigate it better, so I took the easy solution ...

**Comment by ClotildeToullec** [comment]
Ok ok.
Maybe we could reintegrate it but with a deprecation & automatic transformation?
This may also do the work of your 1st solution for you.

**Comment by NicolasAnquetil** [comment]
I found the call to #midasIcon (in FASTTEntity >> inspectionFAST).
This is for a special FAST panel in the inspector, I changed it for #mooseEntity

**Pull request closed without merging**
