### PR TITLE
Search Moose entities using the spotter

### PR DESCRIPTION
**Pull request by badetitou**
With this PR, it is possible to searcg using the spotter some Moose entities.
(I added the basic infrastructure here, it can be improved a lot to display additional information)

image

When you perform a search, it automatically search through the first moose model. 
If there is a lot of data, search in the spotter for the "#Moose" category.

This idea comes from the old moosebook in which the feature was implemented.

### CODE REVIEW

**Comment by badetitou** [comment]
for the baseline, I simply added the new package inside at the end and reformat with default code formatter

**Comment by NicolasAnquetil** [comment]
nice !
but the test coverage decreased by 0.05% :-(

**Comment by badetitou** [comment]
Yeah... I don't know how to test that. I have to find a way by looking at the spotter test :)

**Comment by badetitou** [comment]
I think the PR is ready now :) 
The tests 80% of the processor class and 25 of entry (only printString and so on)

The only issue I see for now is with the icon. However, spotter is expecting an iconName, and our current implement directly provide the icon and not the name (when looking for methods `mooseIcon`)

I propose that we open a new issue to implement `mooseIconName` in places of the current `mooseIcon`, and then we will be able to improve the code here and at some other places.

IMO, this PR is ready for review and can be integrated if everything seems ok

**Comment by jecisc** [comment]
If you have some huges models in the image, does it have an impact on performances?

**Pull request merged**
